name: Check

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  DATABASE_URL: sqlite:///db.sqlite3
  POETRY_VERSION: 1.3.1
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Poetry installation...
        run: |
          pip install poetry==${POETRY_VERSION}
      - name: Python set up...
        uses: actions/setup-python@v4
        with:
          architecture: 'x64'
          python-version: 3.11
          cache: 'poetry'
      - name: Dependencies installation...
        run: poetry install --with dev
      - name: Code check...
        run: |
          poetry run pytest
          poetry run black . --check
          poetry run isort . --check-only
          poetry run mypy .
          poetry run flake8
